In [1]:
import pandas as pd

In [95]:
df = pd.read_excel(r"/Users/pro/Downloads/Pandas_Tutorial/Customer Call List.xlsx")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [96]:
df.drop_duplicates()

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [97]:
df.drop(columns = 'Not_Useful_Column')

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [98]:
df['Last_Name'].str.lstrip('...')

0         Baggins
1           Nadir
2          /White
3         Schrute
4            Snow
5         Swanson
6          Winger
7          Holmes
8             NaN
9          Parker
10         Gamgee
11         Potter
12         Draper
13          Knope
14    Flenderson_
15        Weasley
16          Scott
17           Kent
18         Braton
19      Skywalker
20      Skywalker
Name: Last_Name, dtype: object

In [99]:
#df['Last_Name'] = df['Last_Name'].str.lstrip('...')
#df['Last_Name'] = df['Last_Name'].str.lstrip('/')
df['Last_Name'] = df['Last_Name'].str.strip('123_/,.')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [100]:
#df['Phone_Number'] = df['Phone_Number'].str.replace('[^A-Za-z0-9/|]',  '')
df['Phone_Number']= df['Phone_Number'].apply(lambda x: str(x))

df['Phone_Number'].apply(lambda x: x[0:3] + '-' + x[3:6] + '-' +  x[6:10])

0     123--54-5-54
1     123-/64-3/97
2     706-695-0392
3     123--54-3-23
4     876-|67-8|34
5     304--76-2-24
6            nan--
7     876-|67-8|34
8            N/a--
9     123--54-5-54
10           nan--
11    706-695-0392
12    123--54-3-23
13    876-|67-8|34
14    304--76-2-24
15    123--54-5-54
16    123-/64-3/97
17    706-695-0392
18           N/a--
19    876-|67-8|34
20    876-|67-8|34
Name: Phone_Number, dtype: object

In [101]:
df['Phone_Number'] = df['Phone_Number'].str.replace('N/a', '')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,nan,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,nan,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [102]:
df[["Street", "State", "Zip_Code"]] = df["Address"].str.split(',',  expand = True) 
#df[["Street", "State", "Zip_Code"]] = df["Address"].str.split(',', expand=True).iloc[:, :3].fillna('')

df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Street,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False,93 West Main Street,None,None
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN,True,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True,768 City Parkway,None,None
6,1007,Jeff,Winger,nan,1209 South Street,No,No,False,1209 South Street,None,None
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN,False,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True,25th Main Street,New York,None
10,1011,Samwise,Gamgee,nan,"612 Shire Lane, Shire",Yes,No,True,612 Shire Lane,Shire,None
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False,2039 Main Street,None,None
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,False,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,N/a,Yes,True,N/a,None,None
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True,910 Tatooine Road,Tatooine,None
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True,910 Tatooine Road,Tatooine,None

In [103]:
df["Do_Not_Contact"] = df["Do_Not_Contact"].str.replace('Yes', 'Y')
df["Do_Not_Contact"] = df["Do_Not_Contact"].str.replace('No', 'N')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Street,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,N,True,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Y,False,93 West Main Street,None,None
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN,True,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,N,True,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Y,True,768 City Parkway,None,None
6,1007,Jeff,Winger,nan,1209 South Street,No,N,False,1209 South Street,None,None
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,N,False,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN,False,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,N,True,25th Main Street,New York,None
10,1011,Samwise,Gamgee,nan,"612 Shire Lane, Shire",Yes,N,True,612 Shire Lane,Shire,None
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False,2039 Main Street,None,None
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,N,False,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,False,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,N,False,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,N/a,Y,True,N/a,None,None
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True,910 Tatooine Road,Tatooine,None
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True,910 Tatooine Road,Tatooine,None

In [104]:
#df = df.replace('N/a', '')
#df = df.replace('NaN', '')
df = df.fillna('')

In [115]:
for x in df.index:
    if df.loc[x, "Do_Not_Contact"] == 'Y':
        df.drop(x, inplace =True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Street,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,N,True,123 Shire Lane,Shire,
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,,True,298 Drugs Driveway,,
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,N,True,123 Dragons Road,,
6,1007,Jeff,Winger,nan,1209 South Street,No,N,False,1209 South Street,,
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,N,False,98 Clue Drive,,
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,N,True,25th Main Street,New York,
10,1011,Samwise,Gamgee,nan,"612 Shire Lane, Shire",Yes,N,True,612 Shire Lane,Shire,
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,,True,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False,2039 Main Street,,
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,N,False,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,False,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,N,False,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,,True,3498 Super Lane,,
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True,910 Tatooine Road,Tatooine,
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True,910 Tatooine Road,Tatooine,

In [106]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [116]:
for x in df.index:
    if df.loc[x, "Phone_Number"] == '':
        df.drop(x, inplace =True)
df

#another way to drop null values
df = df.dropna(subset= "Phone_Number", inplace =True)

In [111]:
df.drop(columns = "Address")

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Not_Useful_Column,Street,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,Yes,N,True,123 Shire Lane,Shire,
2,1003,Walter,White,7066950392,N,,True,298 Drugs Driveway,,
4,1005,Jon,Snow,876|678|3469,Y,N,True,123 Dragons Road,,
6,1007,Jeff,Winger,nan,No,N,False,1209 South Street,,
7,1008,Sherlock,Holmes,876|678|3469,N,N,False,98 Clue Drive,,
9,1010,Peter,Parker,123-545-5421,Yes,N,True,25th Main Street,New York,
10,1011,Samwise,Gamgee,nan,Yes,N,True,612 Shire Lane,Shire,
11,1012,Harry,Potter,7066950392,Y,,True,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-2345,Yes,N,False,2039 Main Street,,
13,1014,Leslie,Knope,876|678|3469,Yes,N,False,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-2467,N,N,False,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,No,N,False,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123/643/9775,Yes,N,False,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,7066950392,Y,,True,3498 Super Lane,,
19,1020,Anakin,Skywalker,876|678|3469,Yes,N,True,910 Tatooine Road,Tatooine,
20,1020,Anakin,Skywalker,876|678|3469,Yes,N,True,910 Tatooine Road,Tatooine,

In [114]:
df.reset_index(drop = True)

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Street,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,N,True,123 Shire Lane,Shire,
1,1003,Walter,White,7066950392,298 Drugs Driveway,N,,True,298 Drugs Driveway,,
2,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,N,True,123 Dragons Road,,
3,1007,Jeff,Winger,nan,1209 South Street,No,N,False,1209 South Street,,
4,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,N,False,98 Clue Drive,,
5,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,N,True,25th Main Street,New York,
6,1011,Samwise,Gamgee,nan,"612 Shire Lane, Shire",Yes,N,True,612 Shire Lane,Shire,
7,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,,True,2394 Hogwarts Avenue,,
8,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False,2039 Main Street,,
9,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,N,False,343 City Parkway,,
10,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,False,214 HR Avenue,,
11,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False,2395 Hogwarts Avenue,,
12,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,N,False,121 Paper Avenue,Pennsylvania,
13,1018,Clark,Kent,7066950392,3498 Super Lane,Y,,True,3498 Super Lane,,
14,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True,910 Tatooine Road,Tatooine,
15,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True,910 Tatooine Road,Tatooine,